### ISSUE TITLE
Session waitForLogin() spins in an infinite loop on a bad login request.

### ISSUE THREAD

**Issue by caleb-fringer** [Sepulchre49/instant-messenger#10]
This occurs I think due to the regex used to parse the username/password in the Session.java class. This needs to be handled better and give feedback to the server that this is the cause of the IOException.

Also, need to change or at least make explicit the username/password requirements. At the very least, the username/password validation should be consistent between Server & Session.

**Comment by Sepulchre49** [comment]
Fixed in commit fa90485

**Comment by caleb-fringer** [comment]
Fixed in fa90485
